const GET_ERRORS_REQUEST = 'GET_ERRORS_REQUEST';
const GET_ERRORS_SUCCESS = 'GET_ERRORS_SUCCESS';
const GET_ERRORS_FAILURE = 'GET_ERRORS_FAILURE';

export default {
  GET_ERRORS_REQUEST,
  GET_ERRORS_SUCCESS,
  GET_ERRORS_FAILURE,
};