const GET_SERMONS_REQUEST = 'GET_SERMONS_REQUEST';
const GET_SERMONS_SUCCESS = 'GET_SERMONS_SUCCESS';
const GET_SERMONS_FAILURE = 'GET_SERMONS_FAILURE';
const CREATE_SERMON_REQUEST = 'CREATE_SERMON_REQUEST';
const CREATE_SERMON_SUCCESS = 'CREATE_SERMON_SUCCESS';
const CREATE_SERMON_FAILURE = 'CREATE_SERMON_FAILURE';
const UPDATE_SERMON_REQUEST = 'UPDATE_SERMON_REQUEST';
const UPDATE_SERMON_SUCCESS = 'UPDATE_SERMON_SUCCESS';
const UPDATE_SERMON_FAILURE = 'UPDATE_SERMON_FAILURE';
const DELETE_SERMON_REQUEST = 'DELETE_SERMON_REQUEST';
const DELETE_SERMON_SUCCESS = 'DELETE_SERMON_SUCCESS';
const DELETE_SERMON_FAILURE = 'DELETE_SERMON_FAILURE';

export default {
  GET_SERMONS_REQUEST,
  GET_SERMONS_SUCCESS,
  GET_SERMONS_FAILURE,
  CREATE_SERMON_REQUEST,
  CREATE_SERMON_SUCCESS,
  CREATE_SERMON_FAILURE,
  UPDATE_SERMON_REQUEST,
  UPDATE_SERMON_SUCCESS,
  UPDATE_SERMON_FAILURE,
  DELETE_SERMON_REQUEST,
  DELETE_SERMON_SUCCESS,
  DELETE_SERMON_FAILURE,
}